### ISSUE TITLE
Missing icons for buttons from valo theme

### ISSUE THREAD

**Issue by timcolson** [mstahv/spring-data-vaadin-crud#2]
Great little demo app for Spring Boot + Vaadin!

I fired it up on cmd line on my Mac and saw three "boxes" in the top three buttons.

![missing_icons](https://cloud.githubusercontent.com/assets/1376728/8706396/6cd2a728-2ae4-11e5-9bf6-cbd4d0be60b4.png)

Loaded it into Intellij IDEA, and saw in the readme to try mvn install, still no images. Looks like it cannot find the fonts in the theme and I don't know how to install Vaadin themes, especially in a Spring Boot app.
```
2015-07-15 11:20:22.022  INFO 23667 --- [nio-8080-exec-1] com.vaadin.server.VaadinServlet          : Requested resource [/VAADIN/themes/valo/fonts/open-sans/OpenSans-Light-webfont.woff] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
2015-07-15 11:20:22.022  INFO 23667 --- [nio-8080-exec-7] com.vaadin.server.VaadinServlet          : Requested resource [/VAADIN/themes/base/fonts/fontawesome-webfont.woff] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
2015-07-15 11:20:22.062  INFO 23667 --- [nio-8080-exec-2] com.vaadin.server.VaadinServlet          : Requested resource [/VAADIN/themes/valo/fonts/open-sans/OpenSans-Regular-webfont.woff] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
2015-07-15 11:20:22.130  INFO 23667 --- [nio-8080-exec-4] com.vaadin.server.VaadinServlet          : Requested resource [/VAADIN/themes/base/fonts/fontawesome-webfont.ttf] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
2015-07-15 11:20:22.130  INFO 23667 --- [nio-8080-exec-5] com.vaadin.server.VaadinServlet          : Requested resource [/VAADIN/themes/valo/fonts/open-sans/OpenSans-Regular-webfont.ttf] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
2015-07-15 11:20:22.131  INFO 23667 --- [nio-8080-exec-3] com.vaadin.server.VaadinServlet          : Requested resource [/VAADIN/themes/valo/fonts/open-sans/OpenSans-Light-webfont.ttf] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
```

**Comment by mstahv** [comment]
Should be fixed now with latest changes, I had published a broken version of the "dawn" theme that the project uses. Didn't notice it as I had installed FontAwesome locally :-) Thanks for the heads up and let me know if it still don't work!

**Comment by timcolson** [comment]
Excellent! Thanks, Matti! Super fast reply. I updated, re-ran, and the correct icons are there! :-)

That said, the edit and delete are now grey and disabled (they worked before).
FYI also still getting INFO messages in the log complaining about widgetset additional files.
 
```
2015-07-15 19:28:20.403  INFO 84789 --- [nio-8080-exec-7] com.vaadin.server.VaadinServlet          : Requested resource [/VAADIN/themes/valo/fonts/open-sans/OpenSans-Light-webfont.woff] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
2015-07-15 19:28:20.403  INFO 84789 --- [nio-8080-exec-8] com.vaadin.server.VaadinServlet          : Requested resource [/VAADIN/themes/base/fonts/fontawesome-webfont.woff] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
2015-07-15 19:28:20.466  INFO 84789 --- [nio-8080-exec-9] com.vaadin.server.VaadinServlet          : Requested resource [/VAADIN/themes/valo/fonts/open-sans/OpenSans-Regular-webfont.woff] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
2015-07-15 19:28:20.586  INFO 84789 --- [io-8080-exec-10] com.vaadin.server.VaadinServlet          : Requested resource [/VAADIN/themes/valo/fonts/open-sans/OpenSans-Light-webfont.ttf] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
2015-07-15 19:28:20.586  INFO 84789 --- [nio-8080-exec-1] com.vaadin.server.VaadinServlet          : Requested resource [/VAADIN/themes/base/fonts/fontawesome-webfont.ttf] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
2015-07-15 19:28:20.588  INFO 84789 --- [nio-8080-exec-2] com.vaadin.server.VaadinServlet          : Requested resource [/VAADIN/themes/valo/fonts/open-sans/OpenSans-Regular-webfont.ttf] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
```

```
2015-07-15 19:30:10.172  INFO 84789 --- [nio-8080-exec-8] com.vaadin.server.VaadinServlet          : Requested resource [/VAADIN/themes/valo/fonts/open-sans/OpenSans-Semibold-webfont.woff] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
2015-07-15 19:30:10.189  INFO 84789 --- [nio-8080-exec-9] com.vaadin.server.VaadinServlet          : Requested resource [/VAADIN/themes/valo/fonts/open-sans/OpenSans-Semibold-webfont.ttf] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
```

**Comment by mstahv** [comment]
Damn, I was too tired fixing that last night, so it was only partially fixed. Try once more, if ti still causes issues, I'll remove the dawn theme and fall back to the built in vaadin-themes module.

**Comment by timcolson** [comment]
No error messages in the logs now! :smile: 

Unfortunately, I'm seeing new problems. :disappointed: 

When running from command line via mvn spring-boot:run, icons appear, but rows that *are* selected are still not editable or deletable:
![phonebook_icon_disabled_cmd_line](https://cloud.githubusercontent.com/assets/1376728/8738345/b00f514a-2be2-11e5-8b10-5fba88d49620.png)

When running the Application class from within Intellij IDEA, no icons and disabled edit/delete buttons (like above).

In both cases, if I create a *new entry*, then select that new row, the edit/delete buttons are enabled.





FYI - in Intellij IDEA 14, I got a NPE until I ran mvn install. 

```
2015-07-16 17:41:50.793  INFO 94333 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2015-07-16 17:41:50.796  INFO 94333 --- [           main] crud.Application                         : Started Application in 8.333 seconds (JVM running for 8.906)
2015-07-16 17:42:12.972  INFO 94333 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2015-07-16 17:42:12.973  INFO 94333 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2015-07-16 17:42:12.988  INFO 94333 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 15 ms
2015-07-16 17:42:13.006  WARN 94333 --- [nio-8080-exec-1] c.v.s.DefaultDeploymentConfiguration     : 
=================================================================
Vaadin is running in DEBUG MODE.
Add productionMode=true to web.xml to disable debug features.
To show debug window, add ?debug to your application URL.
=================================================================
2015-07-16 17:42:13.039  INFO 94333 --- [nio-8080-exec-1] c.vaadin.spring.server.SpringUIProvider  : Checking the application context for Vaadin UIs
2015-07-16 17:42:13.042  INFO 94333 --- [nio-8080-exec-1] c.vaadin.spring.server.SpringUIProvider  : Found Vaadin UI [crud.vaadin.MainUI]
2015-07-16 17:42:13.755 ERROR 94333 --- [nio-8080-exec-2] com.vaadin.server.DefaultErrorHandler    : 

java.lang.NullPointerException: null
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
	at com.github.rjeschke.txtmark.Processor.process(Processor.java:154)
	at com.github.rjeschke.txtmark.Processor.process(Processor.java:409)
	at org.markdown4j.Markdown4jProcessor.process(Markdown4jProcessor.java:47)
	at org.vaadin.viritin.label.RichText.withMarkDown(RichText.java:55)
	at org.vaadin.viritin.label.RichText.withMarkDownResource(RichText.java:128)
	at crud.vaadin.MainUI.init(MainUI.java:55)
	at com.vaadin.ui.UI.doInit(UI.java:675)
```

**Comment by mstahv** [comment]
That's weird, it looks like IntelliJ don't for some reason configure the markdown formatted "welcome" message to be on the classpath. That also might have something to do with the buggy enabled state of the action buttons, which works fine for me. Gotta launch my intellij someday and check this out. I have been using NetBeans lately and its just so awesome with maven projects that I tend to forget all configuration issues with Eclipse/IntelliJ.

**Comment by timcolson** [comment]
On a hunch, I updated the project to Spring Boot v1.3.0.M2 -- runs perfectly in Intellij IDEA 14 now. :smiley: 
```
<version>1.3.0.M2</version>
```

**Comment by timcolson** [comment]
And tested with mvn from cmd line - works a treat that way too!

Ran mvn clean, and Intellij would not compile because it could not find "in.virit.WidgetSet", but as noted before, that was solved by running the mvn install goal first, then Intellij was fine.

**Comment by timcolson** [comment]
This makes no sense... I swear, I changed not a single line of code, just re-ran the app. From both Intellij and command line mvn spring-boot:run -- the icons are disabled to edit and delete in Chrome, but work in Safari and Firefox (on Mac). Puzzled.

**Comment by timcolson** [comment]
Reloading a few times in Chrome...and the problem disappeared. I had a red "error-indicator" for a while, but could not find the error, now cannot reproduce.
