### ISSUE TITLE
Unable to resolve com.vaadin.wscdn.WidgetSet even after mvn:install

### ISSUE THREAD

**Issue by boxhead201** [mstahv/spring-data-vaadin-crud#7]
I am using IntelliJ 14.1.  Log of mvn:clean install follows.  It appears the site is down.  How can I use a widget set without having to go to an external site to download it ?

C:\HOMEWARE\ITEC-Toolbox\apps\jdk\jdk1.8.0_25-windows-x64\bin\java "-Dmaven.home=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 14.1\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 14.1\plugins\maven\lib\maven3\bin\m2.conf" -Didea.launcher.port=7533 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 14.1\bin" -Dfile.encoding=windows-1252 -classpath "C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 14.1\plugins\maven\lib\maven3\boot\plexus-classworlds-2.4.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 14.1\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain org.codehaus.classworlds.Launcher -Didea.version=14.1 install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building spring-data-vaadin-crud 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- wscdn-maven-plugin:0.0.1:generate (default) @ spring-data-vaadin-crud ---
Error parsing jar file: file:/C:/Users/prowe030215/Downloads/spring-data-vaadin-crud-master/spring-data-vaadin-crud-master/target/classes
Widgetsets found from classpath:
	org.vaadin.teemu.switchui.SwitchComponentWidgetset in file:/C:/HOMEWARE/maven-2_local/org/vaadin/teemu/switch/2.0.2/switch-2.0.2.jar

Search took 118ms
1 addons widget set found.
Jan 21, 2016 12:30:11 AM com.vaadin.wscdn.client.Connection queryRemoteWidgetSet
SEVERE: Failed to connect service https://wscdn.vaadin.com/api/compiler/compile
javax.ws.rs.ProcessingException: Unable to invoke request
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:287)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:407)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:442)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.post(ClientInvocationBuilder.java:201)
	at com.vaadin.wscdn.client.Connection.queryRemoteWidgetSet(Connection.java:75)
	at com.vaadin.wscdn.VWSCDNMojo.serveFromCDN(VWSCDNMojo.java:250)
	at com.vaadin.wscdn.VWSCDNMojo.execute(VWSCDNMojo.java:191)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.net.UnknownHostException: wscdn.vaadin.com
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:907)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1302)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1255)
	at java.net.InetAddress.getAllByName(InetAddress.java:1171)
	at java.net.InetAddress.getAllByName(InetAddress.java:1105)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:278)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:162)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:283)
	... 33 more

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.234s
[INFO] Finished at: Thu Jan 21 00:30:11 BRT 2016
[INFO] Final Memory: 17M/437M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin.wscdn:wscdn-maven-plugin:0.0.1:generate (default) on project spring-data-vaadin-crud: Remote widgetset compilation failed:  (no response) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1

**Comment by mstahv** [comment]
Hi,

I wonder why your connection is blocked to wscdn.vaadin.com ? Do you have some strict firewall blocking connections from java processes? I'd be eager to know the reasons as we are planning to make the cloud compilation the default option as it is typically much more convenient for developers.

Anyways, I created another branch (without-wscdn) of the example that is using the basic vaadin-maven-plugin to do the widgetset compilation:
https://github.com/mstahv/spring-data-vaadin-crud/tree/without-wscdn

And the actual change:
https://github.com/mstahv/spring-data-vaadin-crud/commit/42522058a2a7a3e3a2d793b8e1c2795b34588cbc

Let me know if that don't work either!

cheers,
matti

**Comment by calaedo** [comment]
Hi,

is it possible to configure a proxy for querying the CDN in maven build @mstahv ? Our corporate Proxy is denying HTTPS request without login.

**Comment by mstahv** [comment]
Have you tried configuring your proxy to generic Java settings? cc @samie

**Comment by calaedo** [comment]
@mstahv well I added proxy configuration for maven in settings.xml.

**Comment by mstahv** [comment]
And problem solved?

**Comment by zygimantus** [comment]
I am also facing similar issue that I cannot download the widgetsets from CDN. Maybe someone can help me?
